version: '3.9'

services:
  app:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - db
    env_file:
      - .env
    command: go run cmd/go_blog/main.go

  db:
    container_name: db
    build:
      context: .
      dockerfile: build/db/Dockerfile
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/mysql
    env_file:
      - .env

volumes:
  db_volume:
