version: '3.9'

services:
  app:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: go_blog
    command: go run cmd/go_blog/main.go

  db:
    container_name: db
    build:
      context: .
      dockerfile: build/db/Dockerfile
    volumes:
      - type: volume
        source: go_blog_db_volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: go_blog

volumes:
  go_blog_db_volume: